# Generated by Django 3.0.6 on 2020-05-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200527_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_model',
        ),
        migrations.RemoveField(
            model_name='document',
            name='model_accuracy',
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('uploaded_date', models.DateField(auto_now_add=True, null=True)),
                ('model_accuracy', models.FloatField(blank=True, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
            ],
        ),
    ]
