# Generated by Django 3.0.6 on 2020-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200527_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
