# Generated by Django 3.0.6 on 2020-05-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200528_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
